import Link from "next/link";
import { BrainCircuit, CalendarDays, Sparkles } from "lucide-react";
import IntelFeedContent from "@/components/dashboard/IntelFeedContent";
import {
  classifyIntelArticle,
  getIntelArticleAccent,
} from "@/lib/intelFeed";
import { formatRelativeTime, resolveRecordDate } from "@/utils/dateFormatter";
import type { GamingNews } from "@/types/api";

interface NewsFeedPanelProps {
  news: GamingNews[];
  fillHeight?: boolean;
  compact?: boolean;
  sectionTitle?: string;
  eyebrow?: string;
}

function resolveNewsDateIso(article: GamingNews): string | null {
  const resolved = resolveRecordDate(article as unknown as Record<string, unknown>);
  return resolved ? resolved.toISOString() : null;
}

export default function NewsFeedPanel({
  news,
  fillHeight = false,
  compact = false,
  sectionTitle = "AI Intelligence Feed",
  eyebrow = "RAG Engine",
}: NewsFeedPanelProps) {
  const panelClass = fillHeight
    ? "glass-panel flex h-full min-h-0 flex-col rounded-3xl p-6 md:p-8 xl:sticky xl:top-24 xl:max-h-[calc(100vh-7rem)]"
    : "glass-panel rounded-3xl p-6 md:p-8";

  const contentClass = fillHeight
    ? "scrollbar-subtle min-h-0 flex-1 overflow-y-auto pr-1"
    : "";

  return (
    <section className={panelClass}>
      <div className="mb-6 flex shrink-0 items-start justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="rounded-2xl border border-fuchsia-400/25 bg-fuchsia-500/10 p-3">
            <BrainCircuit className="h-5 w-5 text-fuchsia-300" />
          </div>
          <div>
            <p className="text-xs font-medium uppercase tracking-[0.35em] text-fuchsia-200/80">
              {eyebrow}
            </p>
            <h2 className="heading-section text-2xl uppercase text-white">
              {sectionTitle}
            </h2>
          </div>
        </div>
        {!compact ? (
          <Link
            href="/intel"
            className="text-[10px] font-medium uppercase tracking-[0.16em] text-fuchsia-200/80 transition hover:text-fuchsia-100"
          >
            Full feed →
          </Link>
        ) : null}
      </div>

      <p className="mb-5 shrink-0 text-xs leading-6 text-slate-400">
        Summaries generated by{" "}
        <span className="font-mono text-fuchsia-200/90">deepseek-coder-v2:16b</span>
        . Error codes and affected regions are highlighted for quick scanning.
      </p>

      <div className={contentClass}>
        {news.length === 0 ? (
          <p className="rounded-2xl border border-dashed border-fuchsia-400/20 px-4 py-10 text-center text-sm text-slate-400">
            [DECRYPTING] No RAG summaries available. Standby for harvester intel...
          </p>
        ) : (
          <div className="space-y-4">
            {news.map((article) => {
              const publishedIso = resolveNewsDateIso(article);
              const kind = classifyIntelArticle(article.title);
              const accent = getIntelArticleAccent(kind);

              return (
                <article
                  key={article.id}
                  className={`rounded-2xl border border-white/8 bg-white/[0.04] p-5 transition hover:bg-white/[0.06] ${accent.borderClass}`}
                >
                  <div className="mb-3 flex flex-wrap items-center gap-2">
                    <span
                      className={`inline-flex items-center gap-1 rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.14em] ${accent.badgeClass}`}
                    >
                      <Sparkles className="h-3 w-3" />
                      {accent.label}
                    </span>
                    <span className="inline-flex items-center gap-1 rounded-full border border-white/10 bg-white/[0.04] px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.14em] text-slate-300">
                      {article.gameTag}
                    </span>
                    <span className="inline-flex items-center gap-1 text-xs text-slate-400">
                      <CalendarDays className="h-3.5 w-3.5" />
                      <time dateTime={publishedIso ?? undefined}>
                        {formatRelativeTime(
                          article.publishedAt ?? article.createdAt,
                        )}
                      </time>
                    </span>
                  </div>

                  <h3 className="mb-3 text-base font-bold leading-snug text-white">
                    {article.title}
                  </h3>

                  <IntelFeedContent content={article.content} />
                </article>
              );
            })}
          </div>
        )}
      </div>
    </section>
  );
}
